# Generated by Django 2.0.2 on 2021-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wl_home', models.CharField(max_length=1)),
                ('pts_home', models.IntegerField(db_column='PTS_home')),
                ('wl_away', models.CharField(max_length=1)),
                ('pts_away', models.IntegerField(db_column='PTS_away')),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSeason',
            fields=[
                ('game_date', models.DateField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'season',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(default='', max_length=45)),
                ('is_active', models.IntegerField()),
                ('birthday', models.DateField()),
                ('school', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=45)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('jersey', models.IntegerField()),
                ('position', models.CharField(max_length=45)),
                ('PTS', models.FloatField(db_column='PTS')),
                ('AST', models.FloatField(db_column='AST')),
                ('REB', models.FloatField(db_column='REB')),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateCity',
            fields=[
                ('city_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'state_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('founded_year', models.IntegerField()),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamNickname',
            fields=[
                ('full_name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3)),
                ('nick_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'team_nickname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, unique=True)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
